ALTER SESSION SET CONTAINER = RABAT_PDB;
ALTER SESSION SET CURRENT_SCHEMA = pdb_admin;

CREATE ROLE site_role;

GRANT SELECT ON CLIENTS TO site_role;
GRANT SELECT ON FOURNISSEURS TO site_role;
GRANT SELECT ON EMPLOYES TO site_role;
GRANT SELECT ON CATEGORIES TO site_role;
GRANT SELECT ON COMMANDES TO site_role;
GRANT SELECT ON PRODUITS TO site_role;
GRANT SELECT ON LigneCommandes TO site_role;
GRANT CREATE SESSION TO site_role;

GRANT site_role TO marrakech_user;
GRANT site_role TO casablanca_user;