-- Connexion au conteneur PDB
ALTER SESSION SET CONTAINER = S1_PDB;
ALTER SESSION SET CURRENT_SCHEMA = pdb_admin;

CREATE DATABASE LINK link_to_global
    CONNECT TO s1_user
        IDENTIFIED BY mon_mdp
    USING '//db-global:1521/RABAT_PDB';

-- Tables
CREATE OR REPLACE SYNONYM CLIENTS         FOR pdb_admin.CLIENTS@link_to_global;
CREATE OR REPLACE SYNONYM FOURNISSEURS    FOR pdb_admin.FOURNISSEURS@link_to_global;
CREATE OR REPLACE SYNONYM EMPLOYES        FOR pdb_admin.EMPLOYES@link_to_global;
CREATE OR REPLACE SYNONYM CATEGORIES      FOR pdb_admin.CATEGORIES@link_to_global;
CREATE OR REPLACE SYNONYM COMMANDES       FOR pdb_admin.COMMANDES@link_to_global;
CREATE OR REPLACE SYNONYM PRODUITS        FOR pdb_admin.PRODUITS@link_to_global;
CREATE OR REPLACE SYNONYM LIGNECOMMANDES  FOR pdb_admin.LIGNECOMMANDES@link_to_global;