-- Connexion au conteneur PDB
CONNECT pdb_admin/Admin123@//localhost:1521/S1_PDB;

-- select the ligne commandes
CREATE TABLE LIGNECOMMANDES1 AS
  SELECT LIGNECOMMANDES.*
  FROM   LIGNECOMMANDES
         JOIN PRODUITS
           ON LIGNECOMMANDES.IDPRODUIT = PRODUITS.IDPRODUIT
  WHERE  LIGNECOMMANDES.QUANTITE > 100
         AND PRODUITS.IDCATEG = 50; 

-- selecting the products
CREATE TABLE PRODUITS1
AS SELECT DISTINCT PRODUITS.*
FROM PRODUITS
JOIN LIGNECOMMANDES1
ON PRODUITS.IDPRODUIT = LIGNECOMMANDES1.IDPRODUIT;

ALTER TABLE PRODUITS1
ADD CONSTRAINT produits1_primary_key
PRIMARY KEY (IDPRODUIT);

-- selecting the commandes
CREATE TABLE COMMANDES1
AS SELECT DISTINCT COMMANDES.*
FROM COMMANDES
JOIN LIGNECOMMANDES1
ON COMMANDES.IDCOMMANDE = LIGNECOMMANDES1.IDCOMMANDE;

ALTER TABLE COMMANDES1
ADD CONSTRAINT commandes1_primary_key
PRIMARY KEY (IDCOMMANDE);

-- selecting the clients
CREATE TABLE CLIENTS1
AS SELECT DISTINCT CLIENTS.*
FROM CLIENTS
JOIN COMMANDES1
ON CLIENTS.IDCLIENT = COMMANDES1.IDCLIENT;

ALTER TABLE CLIENTS1
ADD CONSTRAINT clients1_primary_key
PRIMARY KEY (IDCLIENT);

ALTER TABLE COMMANDES1
ADD CONSTRAINT commandes1_clients1_fk
FOREIGN KEY (IDCLIENT)
REFERENCES CLIENTS1(IDCLIENT)

ALTER TABLE LIGNECOMMANDES1
ADD CONSTRAINT lignecommandes1_produits1_fk
FOREIGN KEY (IDPRODUIT)
REFERENCES PRODUITS1(IDPRODUIT)

ALTER TABLE LIGNECOMMANDES1
ADD CONSTRAINT lignecommandes1_commandes1_fk
FOREIGN KEY (IDCOMMANDE)
REFERENCES COMMANDES1(IDCOMMANDE)