-- Connexion au conteneur PDB
CONNECT pdb_admin/Admin123@//localhost:1521/S1_PDB;

-- select the ligne commandes
CREATE TABLE LIGNECOMMANDES1 AS
  SELECT LIGNECOMMANDES.*
  FROM   LIGNECOMMANDES
         JOIN PRODUITS
           ON LIGNECOMMANDES.IDPRODUIT = PRODUITS.IDPRODUIT
  WHERE  LIGNECOMMANDES.QUANTITE > 100
         AND PRODUITS.IDCATEG = 50; 
