-- Connexion au conteneur PDB
CONNECT pdb_admin/Admin123@//localhost:1521/S2_PDB;

-- select the ligne commandes
CREATE TABLE LIGNECOMMANDES2 AS
  SELECT LIGNECOMMANDES.*
  FROM   LIGNECOMMANDES
         JOIN PRODUITS
           ON LIGNECOMMANDES.IDPRODUIT = PRODUITS.IDPRODUIT
  WHERE  LIGNECOMMANDES.QUANTITE > 50
         AND PRODUITS.IDCATEG = 35; 