-- Connexion au conteneur PDB
CONNECT pdb_admin/Admin123@//localhost:1521/S2_PDB;

-- select the ligne commandes
CREATE TABLE LIGNECOMMANDES2 AS
  SELECT LIGNECOMMANDES.*
  FROM   LIGNECOMMANDES
         JOIN PRODUITS
           ON LIGNECOMMANDES.IDPRODUIT = PRODUITS.IDPRODUIT
  WHERE  LIGNECOMMANDES.QUANTITE > 50
         AND PRODUITS.IDCATEG = 35; 

-- selecting the commandes
CREATE TABLE COMMANDES2
AS SELECT DISTINCT COMMANDES.*
FROM COMMANDES
JOIN LIGNECOMMANDES2
ON COMMANDES.IDCOMMANDE = LIGNECOMMANDES2.IDCOMMANDE;

ALTER TABLE COMMANDES2
ADD CONSTRAINT commandes2_primary_key
PRIMARY KEY (IDCOMMANDE);

-- selecting the clients
CREATE TABLE CLIENTS2
AS SELECT DISTINCT CLIENTS.*
FROM CLIENTS
JOIN COMMANDES2
ON CLIENTS.IDCLIENT = COMMANDES2.IDCLIENT;

ALTER TABLE CLIENTS2
ADD CONSTRAINT clients2_primary_key
PRIMARY KEY (IDCLIENT);

ALTER TABLE COMMANDES2
ADD CONSTRAINT commandes2_clients2_fk
FOREIGN KEY (IDCLIENT)
REFERENCES CLIENTS2(IDCLIENT)

ALTER TABLE LIGNECOMMANDES2
ADD CONSTRAINT lignecommandes2_produits2_fk
FOREIGN KEY (IDPRODUIT)
REFERENCES PRODUITS2(IDPRODUIT)

ALTER TABLE LIGNECOMMANDES2
ADD CONSTRAINT lignecommandes2_commandes2_fk
FOREIGN KEY (IDCOMMANDE)
REFERENCES COMMANDES2(IDCOMMANDE)