-- Connexion au conteneur PDB
ALTER SESSION SET CONTAINER = S2_PDB;
ALTER SESSION SET CURRENT_SCHEMA = pdb_admin;

-- select the ligne commandes
CREATE TABLE LIGHNECOMMANDES2 AS
  SELECT LIGHNECOMMANDES.*
  FROM   LIGHNECOMMANDES
         JOIN produits
           ON LIGHNECOMMANDES.IDPRODUIT = PRODUITS.IDPRODUIT
  WHERE  LIGHNECOMMANDES.QUANTITE > 50
         AND PRODUITS.IDCATEG = 35; 