-- Connect to the root container (CDB$ROOT)
ALTER SESSION SET CONTAINER = CDB$ROOT;

CREATE PLUGGABLE DATABASE B_PDB
  ADMIN USER pdb_admin IDENTIFIED BY Admin123
  ROLES = (DBA)
  DEFAULT TABLESPACE USERS
    DATAFILE '/opt/oracle/oradata/FREE/B_PDB/users01.dbf'
    SIZE 250M AUTOEXTEND ON
  FILE_NAME_CONVERT = (
    '/opt/oracle/oradata/FREE/pdbseed/',
    '/opt/oracle/oradata/FREE/B_PDB/'
  );

ALTER PLUGGABLE DATABASE B_PDB OPEN;

ALTER SYSTEM REGISTER;

ALTER PLUGGABLE DATABASE B_PDB SAVE STATE;

ALTER SESSION SET CONTAINER = B_PDB;

ALTER USER pdb_admin QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION,
      CONNECT,
      RESOURCE,
      CREATE VIEW,
      CREATE TABLE,
      CREATE PROCEDURE,
      CREATE SEQUENCE,
      CREATE TRIGGER,
      CREATE SYNONYM,
      CREATE DATABASE LINK,
      CREATE JOB
TO pdb_admin;

SET SERVEROUTPUT ON;
BEGIN
    DBMS_OUTPUT.PUT_LINE('Schema cree avec succes pour pdb_admin dans BACKUP');
END;
/
