CONNECT pdb_admin/Admin123@//localhost:1521/B_PDB;

-- Mirror tables for the global DB — no FK constraints intentionally,
-- since TRUNCATE order matters and this is a read-only backup target.

CREATE TABLE CATEGORIES (
    IDCATEG          INTEGER       PRIMARY KEY,
    NOMDECATEGORIE   VARCHAR2(100),
    DESCRIPTION      CLOB
);

CREATE TABLE FOURNISSEURS (
    IDFOUR           INTEGER       PRIMARY KEY,
    SOCIETEFOUR      VARCHAR2(100),
    CONTACTFOUR      VARCHAR2(100),
    FONCTIONFOUR     VARCHAR2(100),
    ADRESSEFOUR      VARCHAR2(100),
    VILLEFOUR        VARCHAR2(100),
    REGIONFOUR       VARCHAR2(100),
    CP               VARCHAR2(100),
    PAYSFOUR         VARCHAR2(100),
    TELFOUR          VARCHAR2(100),
    FAXFOUR          VARCHAR2(100)
);

CREATE TABLE EMPLOYES (
    IDEMPLOYE            INTEGER       PRIMARY KEY,
    NOM                  VARCHAR2(100),
    PRENOM               VARCHAR2(100),
    FONCTIONEMPLOYE      VARCHAR2(100),
    TITREDECOURTOISIE    VARCHAR2(100),
    DATEDENAISSANCE      DATE,
    DATEEMBAUCHE         DATE,
    ADRESSEEMPLOYE       VARCHAR2(100),
    VILLEEMPLOYE         VARCHAR2(100),
    PAYSEMPLOYE          VARCHAR2(100),
    TELDOMICILE          VARCHAR2(100)
);

CREATE TABLE CLIENTS (
    IDCLIENT     NUMBER        PRIMARY KEY,
    CODECLIENT   VARCHAR2(100),
    SOCIETE      VARCHAR2(100),
    CONTACT      VARCHAR2(100),
    FONCTION     VARCHAR2(100),
    ADRESSE      VARCHAR2(100),
    VILLE        VARCHAR2(100),
    NAISSANCE    DATE,
    REGION       VARCHAR2(100),
    CP           VARCHAR2(10),
    PAYS         VARCHAR2(100),
    TELEPHONE    VARCHAR2(100),
    FAX          VARCHAR2(100)
);

CREATE TABLE COMMANDES (
    IDCOMMANDE      INTEGER  PRIMARY KEY,
    IDEMPLOYE       INTEGER,
    IDCLIENT        INTEGER,
    DATECOMMANDE    DATE,
    DATELIVRAISON   DATE,
    NMESSAGER       NUMBER(4,0),
    PORTNUMBER      NUMBER(4,0)
);

CREATE TABLE PRODUITS (
    IDPRODUIT                  INTEGER  PRIMARY KEY,
    DESIGNATION                VARCHAR2(100),
    IDFOUR                     INTEGER,
    IDCATEG                    INTEGER,
    PRIXUNITAIRE               FLOAT,
    UNITESENSTOCK              INTEGER,
    UNITESCOMMANDEES           INTEGER,
    NIVEAUREAPPROVISIONNEMENT  INTEGER,
    INDISPONIBLE               INTEGER
);

CREATE TABLE LIGNECOMMANDES (
    IDLIGNECOMMANDE  INTEGER  PRIMARY KEY,
    IDCOMMANDE       INTEGER,
    IDPRODUIT        INTEGER,
    QUANTITE         INTEGER,
    REMISE           FLOAT
);
