-- Connect to the root container (CDB$ROOT)
ALTER SESSION SET CONTAINER = CDB$ROOT;

CREATE PLUGGABLE DATABASE G_PDB
  ADMIN USER pdb_admin IDENTIFIED BY Admin123
  ROLES = (DBA)
  DEFAULT TABLESPACE USERS
    DATAFILE '/opt/oracle/oradata/FREE/G_PDB/users01.dbf'
    SIZE 250M AUTOEXTEND ON
  FILE_NAME_CONVERT = (
    '/opt/oracle/oradata/FREE/pdbseed/',
    '/opt/oracle/oradata/FREE/G_PDB/'
  );

ALTER PLUGGABLE DATABASE G_PDB OPEN;

ALTER SYSTEM REGISTER;

ALTER PLUGGABLE DATABASE G_PDB SAVE STATE;

ALTER SESSION SET CONTAINER = G_PDB;

ALTER USER pdb_admin QUOTA UNLIMITED ON USERS;

BEGIN
   EXECUTE IMMEDIATE 'DROP USER mon_user CASCADE';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -1918 THEN RAISE; END IF;
END;
/

CREATE USER s2_user IDENTIFIED BY mon_mdp
DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;

CREATE USER s1_user IDENTIFIED BY mon_mdp
DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION,
      CONNECT,
      RESOURCE,
      CREATE VIEW,
      CREATE TABLE,
      CREATE PROCEDURE,
      CREATE SEQUENCE,
      CREATE TRIGGER,
      CREATE SYNONYM,
      CREATE PUBLIC SYNONYM,
      CREATE DATABASE LINK,
      CREATE PUBLIC DATABASE LINK
TO pdb_admin;

SET SERVEROUTPUT ON;
BEGIN
    DBMS_OUTPUT.PUT_LINE('Schema cree avec succes dans GLOBAL (Scenario 2)');
END;
/
