-- Connexion au conteneur PDB
ALTER SESSION SET CONTAINER = G_PDB;
ALTER SESSION SET CURRENT_SCHEMA = pdb_admin;

CREATE TABLE CLIENTS 
   (IdClient Number primary key,
CODECLIENT VARCHAR2(100), 
	SOCIETE VARCHAR2(100) NOT NULL, 
	CONTACT VARCHAR2(100) not null, 
	FONCTION VARCHAR2(100) not null,
	ADRESSE VARCHAR2(100), 
	VILLE VARCHAR2(100), 
	NAISSANCE Date,
    REGION VARCHAR2(100),
	CP VARCHAR2(10), 
	PAYS VARCHAR2(100),
    TELEPHONE VARCHAR2(100),
    FAX VARCHAR2(100)
   );
   
 CREATE TABLE "FOURNISSEURS" 
   ("IDFOUR" INTEGER PRIMARY KEY, 
	"SOCIETEFOUR" VARCHAR2(100 CHAR), 
	"CONTACTFOUR" VARCHAR2(100 CHAR), 
	"FONCTIONFOUR" VARCHAR2(100 CHAR), 
	"ADRESSEFOUR" VARCHAR2(100 CHAR), 
	"VILLEFOUR" VARCHAR2(100 CHAR), 
	"REGIONFOUR" VARCHAR2(100 CHAR), 
	"CP" VARCHAR2(100 CHAR), 
	"PAYSFOUR" VARCHAR2(100 CHAR), 
	"TELFOUR" VARCHAR2(100 CHAR), 
	"FAXFOUR" VARCHAR2(100 CHAR)
   ); 
   
 CREATE TABLE "EMPLOYES" 
   ("IDEMPLOYE" Integer PRIMARY KEY, 
	"NOM" VARCHAR2(100 CHAR), 
	"PRENOM" VARCHAR2(100 CHAR), 
	"FONCTIONEMPLOYE" VARCHAR2(100 CHAR), 
	"TITREDECOURTOISIE" VARCHAR2(100 CHAR), 
	"DATEDENAISSANCE" DATE, 
	"DATEEMBAUCHE" DATE, 
	"ADRESSEEMPLOYE" VARCHAR2(100 CHAR), 
	"VILLEEMPLOYE" VARCHAR2(100 CHAR), 
	"PAYSEMPLOYE" VARCHAR2(100 CHAR), 
	"TELDOMICILE" VARCHAR2(100 CHAR)
   );
   
CREATE SEQUENCE compteur
START WITH 1
INCREMENT BY 1;


 CREATE TABLE "CATEGORIES" 
   ("IDCATEG" Integer PRIMARY KEY, 
	"NOMDECATEGORIE" VARCHAR2(100 CHAR), 
	"DESCRIPTION" CLOB
   );
   
CREATE TABLE "COMMANDES" 
   ("IDCOMMANDE" Integer PRIMARY KEY, 
	IDEMPLOYE Integer REFERENCES Employes(IDEMPLOYE),
   	IDCLIENT Integer REFERENCES Clients(IDCLIENT), 
	DATECOMMANDE DATE, 
	DATELIVRAISON DATE, CHECK(DATELIVRAISON >= DATECOMMANDE),
	NMESSAGER NUMBER(4,0), 
	PORTNUMBER NUMBER(4,0)
   );
   
 CREATE TABLE "PRODUITS" 
   ("IDPRODUIT" Integer PRIMARY KEY, 
	"DESIGNATION" VARCHAR2(100 CHAR), 
	"IDFOUR" Integer REFERENCES FOURNISSEURS(IDFOUR), 
	"IDCATEG" Integer REFERENCES CATEGORIES(IDCATEG),  
	"PRIXUNITAIRE" float, 
	"UNITESENSTOCK" Integer, 
	"UNITESCOMMANDEES" Integer, 
	"NIVEAUREAPPROVISIONNEMENT" Integer, 
	"INDISPONIBLE" Integer,CHECK(INDISPONIBLE in (0,1))
   );
   
CREATE TABLE LigneCommandes 
   (    IDLIGNECOMMANDE Integer Primary key,
        IDCOMMANDE Integer REFERENCES COMMANDES(IDCOMMANDE), 
	IDPRODUIT Integer REFERENCES PRODUITS(IDPRODUIT), 
	QUANTITE Integer, 
	REMISE Float
   );